#!/usr/bin/env bash
# Installs the project-factory systemd service. Non-interactive, idempotent.
#
# No factory.timer: factory/main.py runs a persistent state-machine loop
# (plan.md section 6), so a single long-running Restart=on-failure service is
# the right model. A timer only makes sense for a one-shot "wake up, do one
# pass, exit" mode, which isn't what main.py implements.
#
# Usage: sudo bash systemd/install.sh
set -euo pipefail

if [[ "$(id -u)" -ne 0 ]]; then
    echo "error: must be run as root (try: sudo bash systemd/install.sh)" >&2
    exit 1
fi

PROJECT_DIR="/home/factory/project-factory"
UNIT_DIR="/etc/systemd/system"
ENV_FILE="${PROJECT_DIR}/systemd/factory.env"

# Resolve the `claude` CLI path as the factory user (installed per-user via
# nvm, so root's PATH won't see it) and bake it into an EnvironmentFile.
CLAUDE_BIN_DIR="$(sudo -u factory -i bash -lc 'command -v claude' 2>/dev/null | xargs -r dirname || true)"
if [[ -z "${CLAUDE_BIN_DIR}" ]]; then
    echo "warning: could not resolve 'claude' on factory's PATH; factory.env will omit it." >&2
    echo "         fill in CLAUDE_BIN_DIR manually in ${ENV_FILE} before starting the service." >&2
fi

RUNNER_PATH="${PROJECT_DIR}/.venv/bin:${CLAUDE_BIN_DIR:+${CLAUDE_BIN_DIR}:}/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

cat > "${ENV_FILE}" <<EOF
# Generated by systemd/install.sh — safe to re-run to refresh. Not committed
# (see .gitignore).
PATH=${RUNNER_PATH}
EOF
chown factory:factory "${ENV_FILE}"
chmod 640 "${ENV_FILE}"

install -m 644 "$(dirname "$0")/factory.service" "${UNIT_DIR}/factory.service"

systemctl daemon-reload

echo "Installed ${UNIT_DIR}/factory.service and wrote ${ENV_FILE}."
echo
echo "Next steps (not run automatically):"
echo "  systemctl enable --now factory.service"
echo "  systemctl status factory.service"
